# -*- coding: utf-8 -*-
"""
This script converts multiple tif sequences into avi files using ffmpeg. You need
to install ffmpeg fitst to run this script. I use ffmpeg 3.2.2 on Windows 8.1.
Intended to work with tif sequences generated by fast-cam-record. For details, 
go to my website http://www.brain-recording.science
"""

from tkinter import Tk
from tkinter import filedialog
import os

def main():
    Tk().withdraw()
    directory = filedialog.askdirectory()
    tifdirectories = next(os.walk(directory))[1]
    for tifd in tifdirectories:
        os.system("ffmpeg -i " + os.path.join(directory,tifd) + "\\frame%d.tif -vcodec ffv1 " +os.path.join(directory,tifd) + ".avi")

if __name__ == "__main__":
    main()